name: Echo broken Github

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        default: minor
        type: choice
        options:
          - patch
          - minor
          - major
          - keep

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Echo broken Github
        run: | # shell
          echo ${{ github.event.inputs.version }}
          echo "version: ${{ github.event.inputs.version }}"
          if [ "${{ github.event.inputs.version }}" = "keep" ]; then
            echo "version"
          else
            echo "version: ${{ github.event.inputs.version }}"
          fi
