name: Package Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'minor x.1.0'
        type: choice
        options:
        - patch x.x.1
        - minor x.1.0
        - major 1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the dependencies
        run: npm install

      - name: Install vsce
        run: npm install -g vsce

      - name: Package
        run: |
          git config --global user.name "RedCMD"
          git config --global user.email "theredcmd@gmail.com"
          if [[ $(git diff --stat) != '' ]]; then
            echo 'Working directory dirty. Must cleanup first.'
            git clean -d -x -f
          fi
          vsce package ${{ github.event.inputs.version }}
          git add *.vsix
          git commit -m "Package vsix"
          git push