name: Publish Pre-release Extension

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**.json'
      - '**.ts'
      - '**.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: | # vsce etc
          npm i

      - name: Build Extension
        run: | # build `extension.js`'s and `*.wasm` files
          npm run build

      - name: Setup Github Actions
        run: | # allow use of `git push` etc
          git config --global user.name "RedCMD"
          git config --global user.email "theredcmd@gmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync Github Actions"

      - name: Package Extension
        run: | # `.vsix` file
          npx vsce package patch --pre-release
          git push --tags
          echo "VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"

      - name: Generate Release
        run: | # Create release page on github with `.vsix` file
          gh release create v$VERSION --generate-notes --prerelease lag-syntax-highlighter-$VERSION.vsix
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish Pre-release
        run: | # upload to Extension Marketplace
          npx vsce publish --pre-release -p ${{ secrets.VSCE_PAT }}
          git push
