name: Publish Pre-release Extension

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.json'
      - '**.ts'
      - '**.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install vsce
        run: npm i -g @vscode/vsce

      - name: Publish Pre-release
        run: |
          git config --global user.name "RedCMD"
          git config --global user.email "theredcmd@gmail.com"
          vsce publish patch --pre-release -p ${{ secrets.VSCE_PAT }} --no-git-tag-version
          git rm -f *.vsix
          vsce package --no-git-tag-version
          git add -f *.vsix
          npm version patch -f
          git push
