name: Publish Pre-release Extension

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**.json'
      - '**.ts'
      - '**.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: |
          npm i
          npm i @vscode/vsce -g

      - name: Build Extension
        run: npm run build

      - name: Setup Github Actions
        run: |
          git config --global user.name "RedCMD"
          git config --global user.email "theredcmd@gmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync Github Actions"

      - name: Generate Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
         npx vsce package
         echo "VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"
         gh release create v$VERSION --generate-notes lag-syntax-highlighter-$VERSION.vsix
         gh -h
         gh release -h

      - name: Publish Pre-release
        run: |
          vsce publish patch --pre-release -p ${{ secrets.VSCE_PAT }}
          git push
