name: Publish Pre-release Extension

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.json'
      - '**.ts'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install vsce
        run: npm i -g @vscode/vsce

      - name: Install tree-sitter
        run: npm i -g tree-sitter-cli

      - name: Publish Pre-release
        run: |
          git config --global user.name "RedCMD"
          git config --global user.email "theredcmd@gmail.com"
          if [[ $(git diff --stat) != '' ]]; then
            echo 'working directory dirty. must cleanup first'
            git add .
            git commit -m "Sync Github Action"
          fi
          vsce publish patch --pre-release -p ${{ secrets.VSCE_PAT }}
          git push
